import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JLabel;
import java.awt.GridLayout;
import java.util.ArrayList;

public class Manage extends javax.swing.JFrame {

Connection conn;
ResultSet rs,rs1,rs2;
PreparedStatement pst;

    public Manage() {
        initComponents();
        conn = JavaConnect.ConnectDb();
        fillCombo();
       
    }
    
     private JPanel getPanel(ArrayList<String> list) {
        JPanel panel = new JPanel(new GridLayout(0, 1, 5, 5));
        for(int i=0; i<list.size(); i++) {
            JLabel label = new JLabel(list.get(i)); 
            panel.add(label);    
    }

    return panel;
  }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        combo1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        combo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 3, 15)); // NOI18N
        jLabel1.setText("Επιλέξτε Αεροδρόμιο");

        jButton1.setText("Αφαίρεση");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Πληροφορίες");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Πίσω");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 3, 22)); // NOI18N
        jLabel2.setText("Διαχείρηση Αεροδρομίου");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(jLabel2)
                        .addGap(117, 117, 117)
                        .addComponent(jButton3))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(354, 354, 354)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combo1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addContainerGap(192, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(115, 115, 115)
                .addComponent(jButton2)
                .addGap(338, 338, 338))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton3))
                .addGap(58, 58, 58)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(combo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(185, 185, 185))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private int validates()
    {
        int a=0;
        
        int response=JOptionPane.showConfirmDialog(null, "θέλετε σιγουρα να αφαιρέσετε το αεροδρόμιο;","Παράθυρο επιβεβαίωσης",JOptionPane.YES_NO_OPTION);
      if (response==JOptionPane.YES_OPTION){
          a++;
      }
      else {
           setVisible(false);
        Airport ob = new Airport();
        ob.setVisible(true);
      }
      
        return a;
    }
    private void clickAirplaneAndSubstraction()
    {
        String svalue = combo1.getSelectedItem().toString();
     //int response=JOptionPane.showConfirmDialog(null, "θέλετε σιγουρα να αφαιρέσετε το αεροδρόμιο;","Παράθυρο επιβεβαίωσης",JOptionPane.YES_NO_OPTION);
      //if (response==JOptionPane.YES_OPTION){
      try {  
              
           String sql = "Update airport set acquired = 0 where airport_name ='"  +svalue + "'";
           System.out.println(sql);
           pst=conn.prepareStatement(sql);
           pst.executeUpdate();
           JOptionPane.showMessageDialog(null, "Το αεροδρόμιο αφαιρέθηκε με επιτυχία");
           setVisible(false);
           Airport ob = new Airport();
           ob.setVisible(true);
       
      }catch  (Exception e) {
          JOptionPane.showMessageDialog(null, e);
      }
      /*}
      else {
           setVisible(false);
        Airport ob = new Airport();
        ob.setVisible(true);
      }*/
          
       
    }
    
    private void click_info() 
    {
        try {
            String svalue1 = combo1.getSelectedItem().toString();
            
            String sql1="select airport_name,price,coordinates from airport where airport_name='"+svalue1 +"'";
            pst=conn.prepareStatement(sql1);
            rs=pst.executeQuery();
            
            while(rs.next()){
             String name = rs.getString("airport_name");
             String coords = rs.getString("coordinates");
             int price = rs.getInt("price");
             ArrayList<String> list = new ArrayList<String>();
             list.add("airport: " + name);
             list.add("coordinates: " + coords);
             list.add("price: " + Integer.toString(price));
             JOptionPane.showMessageDialog(null, getPanel(list), "info" , JOptionPane.INFORMATION_MESSAGE);
            
            }
           
            
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
    }
    
    private void fillCombo(){
        
        try {
            String sql1="select airport_name from airport where acquired=1";
            pst=conn.prepareStatement(sql1);
            rs=pst.executeQuery();
            
            while (rs.next()) {
                String name= rs.getString(1);
                combo1.addItem(name);
                
            }
            
        }
        
        catch (Exception e) {
             JOptionPane.showMessageDialog(null, e);
        }
    }
    private void combo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo1ActionPerformed
        
    }//GEN-LAST:event_combo1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int b=validates();
        if (b>0)
        clickAirplaneAndSubstraction();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        click_info();
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        setVisible(false);
        Airport ob = new Airport();
        ob.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
